folkehelseinstituttet/Fhi.Smittestopp.App

NDB.Covid19/NDB.Covid19/OAuth2/CustomOAuth2Authenticator.cs

Added prompt login parameter to force users to login via ID porten every time they give consent

[48511] Force users to login to ID porten

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml

- Changed text color on developer tools from white to blue

[49894] - Changed text color for developer tools

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_paragraph.xml
NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs

Updated text styling of consent pages

[49863] Updated text styling of consent pages

---

NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/Questionnaire.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs

Enforcing wheels to be a preffered datepicker style and setting minimum date for symptoms onset date to be 1st of November

[50030] [UI] Questionnaire: Symptom onset

---

NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs

- Adjusted font weights and sizes on consent page according to design

[49903] Fixed margin issue on consent page appearing on iPhone SE Gen 1

---

NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json

- Added https to link
- Updated excel sheet accordingly

[50160] Bugfix - Fixed url in 'About' page

---

NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs

Added italic font to bottom section of consent 1 pages in accordance with the design

[50153] Bugfix, iOS - Added italic font to consent 1 pages

---

NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/infection_status_tile_border.xml
NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml

[50237] Android: Added border and new background color to tiles

---

NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs

[50490] Android: Display correct message page header text depending on number of messages

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.designer.cs
NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json
NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs

- Removed from both Android and iOS
- Updated excel sheet
**Android**
**iOS**

[50491] Bugfix/Change request: Removed section from general settings

---

NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs

Implemented check for active modal presentation in status bar color logic

[50516] iOS: Fixed issue where status bar color persisted in consent 2 page

---

NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs

[50559] iOS: Wrong header text color in settings page

---

NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard

- Removed spacing from stack views

[50562] iOS: Inconsistent spacing across pages in burger menu

---

NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
NDB.Covid19/NDB.Covid19/ViewModels/MessagesViewModel.cs

Fixed async error in notification manager

[50586] Removed unnecessary async in messaging

---

NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
NDB.Covid19/NDB.Covid19/ViewModels/MessagesViewModel.cs

[50562] iOS: Inconsistent spacing across pages in burger menu
Removed unnecessary async in messaging (#125)

Merged fix for build break on android

---

NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard

Horizontally aligned stack view with label and switch to center of parent

[50597] iOS: Fixed alignment issue with small screen/large font on onboarding consent page

---

NDB.Covid19/NDB.Covid19.iOS/Permissions/IOSPermissionManager.cs

[Issue-4] Remove outdated comment

---

NDB.Covid19/NDB.Covid19/Locales/en.json

- Updated .json file
- Update excel sheet

[50728] Correction of english link

---

NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs

Fix crash on wake up call (#145)

Merge from dev to master with hotfix for crash on wake up call

---

NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json

Added missing notification texts (#147)

Merge from dev to master on 09.12.2020

---

NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
NDB.Covid19/NDB.Covid19/Enums/NotificationType.cs
NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json

[Cherry-pick] Fix messages after wake up service call (#148)
* Fix messages after wake up service call
* Change intent filter
* Use LocalBroadcastManager instead of regular one

Merge dev to master on 09-12-2020

---

NDB.Covid19/NDB.Covid19/Configuration/Conf.cs

Added links to store that will be used in 410 error in the future

Added links to stores in Conf.cs

---

NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
NDB.Covid19/NDB.Covid19/Locales/nn.json
NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
NDB.Covid19/NDB.Covid19/OAuth2/AuthenticationManager.cs
README.md

Update README.md (#157)
[50875] Bugfix - Update of header text for nynorsk on error page (#158)
Updated JWT-nuget package and added an allowed time skew of 5 minutes for validation of the nbf-claim in tokens. (#61)
Added links to stores in Conf.cs (#159)

Merge from dev to master on 11-12-2020

---

NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
NDB.Covid19/NDB.Covid19/Locales/nn.json

Fixed error in status text header for Nynorsk

[51084] Added accessibility label to status text header on main page

---

NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard

[50565] iOS: Unified text spacing in consent views

---

NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard

[50565] iOS: Fixed inconsistent margins in consent 2 page

---

NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard

[52125] Increased spacing in what is new page

---

NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json

- Enabled auto restart on language setting change
- Changed text in dialog when changing language (sheet updated)

[52221] Enabled auto restart on language change

---

NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/nb.json

Updated text in country questionnaire page informing about selecting no countries shares the keys with all countries

[51632] Updated text in country questionnaire page

---

NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs

- Adjusted text size on What is new page to match onboarding pages
- Added scroll bar flashing on what is new page to match behaviour of onboarding pages

[52676] iOS: Adjusted font size in What is new page 

---

NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs

Fixes #268 
Should also fix #222

[52661, 52538] Bypass location check from Android 11 (API 30) and above

---

NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard

Replaced StackView with View to have more control over spacing

[53043] iOS: Adjusted spacing in what is new page 

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_bullet.xml
NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs

Replaced checkbox with imageview and textview

[53102] Android: Fixed screen reader issue in what is new page

---

NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard

[53079] iOS: Adjusted what is new page to scale better with screen and font size

---

NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs

- Fixed the bug
- Refactored viewcontroller code a bit

[52686] Fixed UI bug where arrow and text where overlapping

---

NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
NDB.Covid19/NDB.Covid19/Configuration/Conf.cs

Added additional structure to the storyboard to force screen reader to read elements in correct order.

[53781] iOS: Screen reader support for the new page "Dagens tall"

---

NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs

Due to recent discoveries, some props of common XPlat DSC is actually causing troubles for Android. 
Added Infectiousness for each DSOS in -14 to 14 days, uncommented dictionaries that lead to exception on Android

Rework mock configuration for EN API v2

---

NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json

**Screenshots**
Bokmål:
Nynorsk:

[55493] Key Figures: small letters in covid-19

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperTools.storyboard
NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperToolsViewController.cs
NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperToolsViewController.designer.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDailySummaryJsonHelper.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDetectedHelper.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureWindowJsonHelper.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/JsonCompatibleExposureDailySummary.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/JsonCompatibleExposureWindow.cs
NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/DeveloperToolsService.cs
NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/IDeveloperToolsService.cs
NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/ReleaseToolsService.cs
NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs

Feature/53767 initial implementation of ExposureStateUpdatedAsync handler method + add print Buttons to DevTools

---

NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs

* Implemented new feature flag name and new DTO property names
* Updated to latest version of AnonymousTokens nuget packages (including related simplifications from ECPublicKeyParameters -> ECPoint)
* Changed : to _ in anonymous tokens feature flag

New AnonymousTokens feature flag and updated property namings (#291)

---

NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
NDB.Covid19/NDB.Covid19/Locales/nn.json

[55820] Removed colon in nynorsk text and fixed alignment in key numbers page

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs

- iOS: Changed which label that gets focus from voiceover in message page
- Android: Corrected margins in key numbers page
- Android: Moved line count alignment to OnWindowFocusChanged (line count is 0 in OnCreate) to fix vertical alignment issue

Android: Fixed alignment issues. iOS: Fixed which label that gets focus in message page

---

NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
NDB.Covid19/NDB.Covid19.Droid/Utils/DiagnosisKeysDataMappingUtils.cs
NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs

Implemented required DiagnosisKeysDataMapping to tell API how to translate data from TEK to ExposureWindows, added checks for EN API v1 calling it as well as pref to call this method not more often than once in a week

[53767] Android: Add DiagnosisKeysDataMapping

---

NDB.Covid19/NDB.Covid19/Locales/ar.json
NDB.Covid19/NDB.Covid19/Locales/en.json
NDB.Covid19/NDB.Covid19/Locales/lt.json
NDB.Covid19/NDB.Covid19/Locales/nb.json
NDB.Covid19/NDB.Covid19/Locales/nn.json
NDB.Covid19/NDB.Covid19/Locales/pl.json

Fixing small text bugs, and unifying time format in text for BOK, NN, EN, LT and PL

Fix bug 56194 and 56195

---

NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ExposureDetectedTests.cs
NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDetectedHelper.cs
NDB.Covid19/NDB.Covid19/Models/DailySummaryConfigurationDTO.cs
NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs

Added evaluation of MaximumRiskScore against a threshold received from backend.

[53767] Risk scoring EN API v2

---

NDB.Covid19/NDB.Covid19/Models/DTOsForServer/LogDTO.cs

[56580] [Issue 40] Wrong field used for correlation

---

NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
NDB.Covid19/NDB.Covid19.Droid/Resources/layout/background_activity_dialog.xml
NDB.Covid19/NDB.Covid19.Droid/Utils/BatteryOptimisationUtils.cs
NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs

Fixing logic for displaying battery optimization dialog as well as updating keys logic.

Bugfix/battery optimization dialog logic / update keys logic 

---

NDB.Covid19/NDB.Covid19.Droid/appcenter-pre-build.sh
NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh

Deleted unused variable from appcenter-pre-build.sh both IOS and Droid project.

[Issue 57] - Delete unused appcenter variable

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml

Correcting order of accessibility reading.

Bugfix - [Android] Fixing order of accessibility (screen reader) Key Figures page

---

NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml

Changing order of screen reader on key figures page

Bugfix - Screen reader key figures page

---

NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs

Modified GetDateFromDateTime method to be able to change culture for specific fields.

 [59239] [Bugfix] - Somali spellings errors on key figures page

---

NDB.Covid19/NDB.Covid19/Locales/ur.json

[59315, 59312, 59316] Bugfix Urdu text

---

NDB.Covid19/NDB.Covid19/Locales/ur.json

[59311] Bugfix Urdu date text on message page
